# Generated by Django 5.1.3 on 2024-11-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=100)),
                ('conductor', models.CharField(max_length=255)),
                ('fecha_programada', models.DateField()),
                ('notas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RutaLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=100)),
                ('conductor', models.CharField(max_length=255)),
                ('fecha_programada', models.DateField()),
                ('notas', models.TextField()),
            ],
        ),
    ]
