# Generated by Django 5.1.3 on 2024-11-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=100)),
                ('conductor', models.CharField(max_length=255)),
                ('fecha_programada', models.DateField()),
                ('notas', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='route',
            old_name='destination',
            new_name='ruta',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='route',
            name='origin',
        ),
        migrations.AddField(
            model_name='route',
            name='conductor',
            field=models.CharField(default='desconocido', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='fecha_programada',
            field=models.DateField(default='2024-11-22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='notas',
            field=models.TextField(default='no hay notas'),
            preserve_default=False,
        ),
    ]
